eureka:
  instance:
    prefer-ip-address: true

spring:
  profiles:
    active: dev

# 基本取消超时
ribbon:
  ReadTimeout: 60000
  SocketTimeout: 60000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  retryableStatusCodes: 404,502
