eureka:
  instance:
    prefer-ip-address: true

spring:
  profiles:
    active: dev

# 2.5s 超时
ribbon:
  ReadTimeout: 2500
  SocketTimeout: 2500
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  retryableStatusCodes: 404,502
