name: Test Researcher Entity Service

on:
  push:
    branches:
      - develop
    paths:
      - entity-researcher/**

jobs:
  test:
    name: Unit Tests & Integration Tests
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: entity-researcher

    steps:
      - uses: actions/checkout@v2

      - name: Cache Maven Repo
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Maven Test
        run: mvn -B clean test -Dspring.profiles.active=test

      - name: Maven Verify
        run: mvn -B clean test -Dspring.profiles.active=test

      - name: Quality Analysis
          run: |
            mvn sonar:sonar \
            -Dsonar.projectKey=org.NJU-SE-17-advanced-se:entity-researcher \
            -Dsonar.host.url={{ secrets.SONAR_HOST }} \
            -Dsonar.login={{ secrets.ENTITY_RESEARCHER_SONAR_TOKEN }}
